name: twine

up:
  - node:
      version: v12.16.3
      packages:
        - .
  - ruby:
      version: 2.7.2
  - bundler


commands:
  test:
    syntax: ""
    desc: 'Run Twine tests'
    run: node_modules/.bin/testem ci
